export const jsondata: string = JSON.stringify(
  {
    users: [
      {
        id: 1,
        name: "Olivia Carter",
        age: 26,
        country: "United States",
        avatar: "https://picsum.photos/seed/olivia/400/400.jpg",
      },
      {
        id: 2,
        name: "Liam Anderson",
        age: 32,
        country: "Canada",
        avatar: "https://picsum.photos/seed/liam/400/400.jpg",
      },
      {
        id: 3,
        name: "Emma Wilson",
        age: 24,
        country: "Australia",
        avatar: "https://picsum.photos/seed/emma/400/400.jpg",
      },
      {
        id: 4,
        name: "Noah Williams",
        age: 29,
        country: "United Kingdom",
        avatar: "https://picsum.photos/seed/noah/400/400.jpg",
      },
      {
        id: 5,
        name: "Sophia Martinez",
        age: 35,
        country: "Spain",
        avatar: "https://picsum.photos/seed/sophia/400/400.jpg",
      },
      {
        id: 6,
        name: "James Taylor",
        age: 41,
        country: "Germany",
        avatar: "https://picsum.photos/seed/james/400/400.jpg",
      },
      {
        id: 7,
        name: "Ava Thompson",
        age: 27,
        country: "India",
        avatar: "https://picsum.photos/seed/ava/400/400.jpg",
      },
      {
        id: 8,
        name: "William Brown",
        age: 38,
        country: "France",
        avatar: "https://picsum.photos/seed/william/400/400.jpg",
      },
      {
        id: 9,
        name: "Mia Davis",
        age: 31,
        country: "Japan",
        avatar: "https://picsum.photos/seed/mia/400/400.jpg",
      },
      {
        id: 10,
        name: "Lucas Miller",
        age: 23,
        country: "Brazil",
        avatar: "https://picsum.photos/seed/lucas/400/400.jpg",
      },
    ],
    company: "LumiVizStack",
  },
  null,
  2,
);